#include <string.h>
#include <stdio.h>
#include <sys/types.h>
#include <sys/socket.h>
#include <string>
#include <map>
#include <list>
#include <fstream>
#include <jni.h>
#include <dlfcn.h>
#include <stddef.h>
#include <fcntl.h>
#include <dirent.h>
#include <sys/syscall.h>
#include <cstdio>
#include <unistd.h>
#include <stdlib.h>
#include <syscall.h>
#include <bits/getopt.h>
#include <asm/unistd.h>
#include <asm/fcntl.h>
#include <bits/getopt.h>
#include <arpa/inet.h>
#include <netpacket/packet.h>
#include <net/ethernet.h>
#include <istream>
#include <netinet/in.h>
#include <net/ethernet.h>
#include <errno.h>
#include <netinet/ip.h>
#include <netdb.h>
#include <sys/system_properties.h>
#include "lsplant.hpp"
#include "Utils/elf_util.h"
#include "HookUtils.h"
#include "hook/xhook/include/xhook.h"
#include "netlink/ifaddrs.h"
#include "netlink/bionic_netlink.h"
#include "includes/ZhenxiLogging.h"
#include "includes/ZhenxiLog.h"
#include "includes/adapter.h" //vm
#include "includes/parse.h"
#include "includes/JnitraceForC.h"
#include "includes/stringHandler.h"